name: Deploy-Staging-Production

on:
  workflow_dispatch:

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://example.com
    steps:
      - run: echo deploy staging

  deploy_sandbox:
    runs-on: ubuntu-latest
    environment:
      name: sandbox
    steps:
      - run: echo deploy staging
  
  deploy_production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    steps:
      - run: echo deploy production
      - run: sleep 60
