name: Deploy-Staging-Production

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "branch name"
        required: false
        default: "main"
      environment:
        description: "環境"
        required: true
        type: choice
        options:
          - sandbox001
          - sandbox002
          - sandbox003
          - sandbox004
          - sandbox005
          - staging
          - mirror
          - production

env:
  GITHUB_SHA: ${{ inputs.branch }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Deploy
        run: echo deploy ${{ github.event.inputs.environment }}
      - name: Sleep
        run: sleep 60

  # deploy_staging:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: staging
  #     url: https://example.com
  #   steps:
  #     - run: echo deploy staging

  # deploy_sandbox:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: sandbox
  #   steps:
  #     - run: echo deploy staging

  # deploy_production:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: production
  #     url: https://example.com
  #   steps:
  #     - run: echo deploy production
  #     - run: sleep 60
